implemented issues 16 and 19
han16nah/my-ssd-test-repo pull request #24
Opened 2022-03-07 15:28 UTC by vivienzahs

- Implemented issues 16 and 19.
- Added suggestion for how to handle user input (currently commented out)

Closed issues:

- Closes #16 
- Closes #19

2022-03-07 21:05 UTC, han16nah requested changes
I added some comments to sections that may be changed.

Let's decide tomorrow whether to use ReStructuredText (like you did here) or Google format (like I did in #21) for the docstrings

Add some point, we should add type hints (in a new issue/PR, once we implemented rsmaining methods), e.g. 
```python
def read_csv_as_df(self, file_in: str, col_separator: str = " ", skip_initial_space: bool = True) -> None:
```

2022-03-07 21:05 UTC, han16nah commented on src/oop_analysis.py
> +        self.table_name = table_name
not sure if this one is needed

2022-03-08 11:59 UTC, vivienzahs commented on src/oop_analysis.py
> +            print('header_outfile is"', header_outfile)
Yeah, I think its is only two different modules doing similar things. Found this quite nice, but is still commented out and open for discussion. I am fine with either modules.

2022-03-08 12:35 UTC, vivienzahs commented
I have included all the changes and have solved the conflicts. I think this branch can now be merged with the main branch.

2022-03-08 15:34 UTC, merged